### ISSUE TITLE
Maturity of your project

### ISSUE THREAD

**Issue by petitchamp** [zieitokk/Digging-into-self-supervised-monocular-depth-estimation#1]
Hello,
I am look for an implementation of this paper _Digging Into Self-Supervised Monocular Depth Estimation_

Is your code ready to run or it needs further development?
Could you provide some documentation please?

**Comment by zieitokk** [comment]
> Hello,
> I am look for an implementation of this paper _Digging Into Self-Supervised Monocular Depth Estimation_
> 
> Is your code ready to run or it needs further development?
> Could you provide some documentation please?

Sorry for the late reply.
The code that is `ALMOST` the same as Monodepth, except that I wrote it into keras version.

The initial idea was to implement the digging into self supervised monocular depth estimation with keras, however, the author has already implemented it so far. So you may check it at https://github.com/nianticlabs/monodepth2

Sorry for the misguidance by the title
